services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env.prod
    environment:
      DATABASE_URL: ${DATABASE_URL:-} # Use variável do Compose ou valor padrão do .env.prod
      SECRET_KEY: ${SECRET_KEY:-} # Prioriza o Compose, caso especificado
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
