services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env.prod
    environment:
      DATABASE_URL: ${DATABASE_URL:-mysql://user:password@db:3306/my_database} # Use variável do Compose ou valor padrão
      SECRET_KEY: ${SECRET_KEY:-} # Prioriza o Compose, caso especificado
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
